name: Check and create tag
on:
  push:
    branches:
      - master
    paths:
      - vspreview/_metadata.py

jobs:
  new_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Get version number
        run: |
          echo "CURR_VER=v$(python -c "import runpy;runpy.run_path('vspreview/_metadata.py', None, '__github__')")" >> $GITHUB_ENV
      - name: Check if version exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: mukunku/tag-exists-action@v1.6.0
        id: tagcheck
        with:
          tag: ${{ env.CURR_VER }}

      - name: Make tag
        uses: actions/github-script@v8
        if: steps.tagcheck.outputs.exists == 'false'
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.CURR_VER}`,
              sha: context.sha
            })
      - name: Fallback
        if: steps.tagcheck.outputs.exists == 'true'
        run: echo "Nothing to see here, move along citizen"
