name: Publish releases to PyPI
on:
  push:
   tags:
      - v[0-9]+**

jobs:
    package_build:
        name: Build and push to PyPI
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Prep Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.11'

        - name: Install build tools
          run: |
              python -m pip install build setuptools twine --user
          continue-on-error: false
        - name: Build wheel
          id: wheel
          run: |
              python -m build --wheel --outdir dist/
          continue-on-error: true
        - name: Build source distribution
          id: sdist
          run: |
            python -m build --sdist --outdir dist/
          continue-on-error: true
        - name: Check the output
          run: |
            python -m twine check --strict dist/*
          continue-on-error: false
        - name: Die on failure
          if: steps.wheel.outcome != 'success' && steps.sdist.outcome != 'success'
          run: exit 1
        - name: Publish to PyPI
          uses: pypa/gh-action-pypi-publish@master
          with:
            user: __token__
            password: ${{ secrets.PYPI_TOKEN }}