name: Test VapourSynth workflow

on: workflow_dispatch

jobs:
  setup-vs:
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/actions/setup-vapoursynth
        with:
          vapoursynth-version: 70
